### PR TITLE
changed biocontainer to samtools:1.9

### LINKED ISSUE #22: feat: samtools update in singularity containers
We have just updated `samtools` to version to `1.9` from bioconda, the previous one raised errors, see [here](https://github.com/merenlab/anvio/issues/1479).
We should do the same for singularity runs too, to use the same versions of tools consistently.

### PR DESCRIPTION
**Pull request by noepozzan**
## Description

changed the Snakefile to have biocontainer with samtools:1.9

Fixes #22 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code changes follow the style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] I have updated the project's documentation

### CODE REVIEW

**Comment by AngryMaciek** [comment]
@noepozzan : did you also test on the cluster?

**Comment by noepozzan** [comment]
> @noepozzan : did you also test on the cluster?

yes, singularity on cluster worked for me.

**Review by mkatsanto — APPROVED** [review]

**Comment by mkatsanto** [comment]
@noepozzan you can merge the branch

**Comment by noepozzan** [comment]
> @noepozzan you can merge the branch

thank you!

**Pull request merged**
