### PR TITLE
ci: transfer current ci tests from GitLab framework into GitHub Actions

### LINKED ISSUE #4: ci: set up GitHub Actions

### PR DESCRIPTION
**Pull request by AngryMaciek**
* remove gitlab ci configuration in YAML format
* add github actions configuration in YAML format (running exactly the same tests)
* add missing shields in _README.md_

Fixes #4

### CODE REVIEW

**Comment by AngryMaciek** [comment]
CI ready! @uniqueg ∨ @fgypas ∨ @mkatsanto - please take a look.

**Comment by fgypas** [comment]
Do we have unlimited time for github actions? My opinion is to run the CI only on merge requests on dev and master and not for every commit (and branch).

**Comment by AngryMaciek** [comment]
> Do we have unlimited time for github actions? My opinion is to run the CI only on merge requests on dev and master and not for every commit (and branch).

Yes, we do. Actions are free for public repos so I see no reason to turn them off <?>

**Review by fgypas — APPROVED** [review]
LGTM

**Comment by fgypas** [comment]
@AngryMaciek Please don't forget to squash and merge.

**Pull request merged**
