### PR TITLE
feat: fastqc after trimming

### LINKED ISSUE #30: Fastqc report after adapter trimming
**Is your feature request related to a problem? Please describe.**
The current fastqc is applied to the raw fastq files. However it is still relevant for the user to see what the quality of reads is or if there are still overrepresented sequences after the trimming. 

**Describe the solution you'd like**
Introduce a second rule fastqc_trimmed, where the trimmed fastq file is used as input.

### PR DESCRIPTION
**Pull request by ninsch3000**
## Description

rule for fastqc after trimming

Fixes #30 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation updated

## Checklist:

- [x] My code changes follow the style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] I have updated the project's documentation

### CODE REVIEW

**Comment by ninsch3000** [comment]
HELP WANTED
files are created but don't show up in multiqc summary.  
fastgc_trimmed

**Comment by dominikburri** [comment]
> HELP WANTED files are created but don't show up in multiqc summary. fastgc_trimmed

Yeah it could be because of this issue I describe here https://github.com/zavolanlab/zarp/issues/30#issuecomment-1066721519. I think it has something to do with the file names.

**Comment by ninsch3000** [comment]
I give up. I tried all combinations of `.` and `_`  and replacing `mate` with `fq`, but couldn't solve it.   

Would be good if someone else tried, there must be one combination that evaded me ;)

**Comment by AngryMaciek** [comment]
Maybe it would be an option to specify the parsing within the General Statistics table in the MultiQC configfile?

https://multiqc.info/docs/#custom-content

**Comment by AngryMaciek** [comment]
@mkatsanto : best would be to unify the "duplicated" rows (i.e. corresponding to the same sample but different processing stage, thus a different suffix).

**Comment by mkatsanto** [comment]
Ok, made it like this:
Screenshot 2022-03-16 at 21 33 35
What do you think? @ninsch3000 @AngryMaciek @dominikburri  ? 
I still need to change the tests since I changed the naming scheme in some rules, so will push later the updated branch.

**Comment by ninsch3000** [comment]
Great @mkatsanto !! 
I'm curious to see how you solved it..

Yes, tests still have to be updated, but also the documentation, esp. `pipeline_documentation.md`

**Comment by AngryMaciek** [comment]
Looks good, I understand that in the end you did change the names, not configuration?  
That's OK too as far as I am concerned...

**Comment by dominikburri** [comment]
> Ok, made it like this:
> Screenshot 2022-03-16 at 21 33 35
> What do you think? @ninsch3000 @AngryMaciek @dominikburri ?
> I still need to change the tests since I changed the naming scheme in some rules, so will push later the updated branch.

Thank you @ninsch3000 and @mkatsanto, I think it looks good now.
Best would be to also test it with a real-life sample to see how it holds up, but it's not necessary I think. 

How I understand it:
* Single-end: always one row.
* Paired-end: two rows, where first half of columns for each mate, second half (about mapping statistics) only displayed at mate 1.

**Review by fgypas — APPROVED** [review]
Looks good to me. The only question I have is whether we need all these png files in the md5sum, but if the tests pass then it should be fine.

**Pull request merged**
