### PR TITLE
Update git repo link on REAME.md

### LINKED ISSUE #2: docs: update links/info referring to old repository
Currently there are still some links from gitlab, e.g. on how to clone the repository. 
This should be replaced by the new links.

### PR DESCRIPTION
**Pull request by fgypas**
Update git repo link on REAME.md. Fixes #2

### CODE REVIEW

**Comment by AngryMaciek** [comment]
@fgypas : thanks for the quick fix; are you sure that was the only place to correct the URL? (ex. could you `grep` recursively for `git@git.scicore.unibas` ?)

**Review by AngryMaciek — APPROVED** [review]
@fgypas : thanks for the quick fix; are you sure that was the only place to correct the URL? (ex. could you `grep` recursively for `git@git.scicore.unibas` ?)

**Comment by fgypas** [comment]
> @fgypas : thanks for the quick fix; are you sure that was the only place to correct the URL? (ex. could you `grep` recursively for `git@git.scicore.unibas` ?)

@AngryMaciek I tried the following and I could not find something else:
```
grep -rl "scicore" zarp
grep -rl "gitlab" zarp
```

**Comment by AngryMaciek** [comment]
I have noticed that the GitHub Action for setting up _conda_ envs is bahaving a little strange - sometimes it gets stuck on building the main environment. I think this is an issue on their end, not ours, so I opened an issue: https://github.com/conda-incubator/setup-miniconda/issues/196 Meanwhile, if this happens here, one needs to re-start the CI workflow.

**Pull request merged**
